### ISSUE TITLE
无法回复楼里，只能单独开楼bug

### ISSUE THREAD

**Issue by bilibili2233a** [HuanCheng65/TiebaLite#100]
![Screenshot_20220516_115141_com.huanchengfly.tieba.post.jpg](https://user-images.githubusercontent.com/99982054/168516978-922fdc24-864e-450e-8688-b50df458840c.jpg)
一回复就显示报错：
java.io.EOFException: End of input at line 1 column 1 path $
	at x0.a.X(JsonReader.java:6)
	at x0.a.u(JsonReader.java:20)
	at x0.a.c0(JsonReader.java:2)
	at t0.i$b.b(ReflectiveTypeAdapterFactory.java:1)
	at l1.c.a(GsonResponseBodyConverter.java:2)
	at l1.c.convert(GsonResponseBodyConverter.java:1)
	at j1.d.b(NullOnEmptyConverterFactory.kt:2)
	at j1.d.a(Unknown Source:0)
	at j1.c.convert(Unknown Source:4)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:7)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:1)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by HuanCheng65** [comment]
回铁相关后续不再维护，推荐使用官方客户端回贴
