### ISSUE TITLE
切回界面时崩溃

### ISSUE THREAD

**Issue by yxom-alt** [HuanCheng65/TiebaLite#108]
App 版本：4.0.0.36.dev-9
                                      系统版本：9
                                      机型：Xiaomi Redmi 8
                                      
                                      崩溃：
                                      java.lang.NullPointerException: null
at com.huanchengfly.tieba.post.activities.ThreadActivity.b1(ThreadActivity.kt:2)
at com.huanchengfly.tieba.post.activities.ThreadActivity.f0(ThreadActivity.kt:1)
at com.huanchengfly.tieba.post.activities.ThreadActivity$o.onResponse(ThreadActivity.kt:1)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:3)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.b(null:0)
at retrofit2.b.run(null:6)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6861)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by yxom-alt** [comment]
App 版本：4.0.0.36.dev-9
                                      系统版本：9
                                      机型：Xiaomi Redmi 8
                                      
                                      崩溃：
                                      java.lang.NullPointerException: null
at com.huanchengfly.tieba.post.activities.ThreadActivity.b1(ThreadActivity.kt:2)
at com.huanchengfly.tieba.post.activities.ThreadActivity.f0(ThreadActivity.kt:1)
at com.huanchengfly.tieba.post.activities.ThreadActivity$o.onResponse(ThreadActivity.kt:1)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:3)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.b(null:0)
at retrofit2.b.run(null:6)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6861)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Xnjikol** [comment]
在点开浏览历史时崩溃

                                      App 版本：4.0.0.36.dev-9
                                      系统版本：10
                                      机型：HUAWEI ELE-AL00
                                      
                                      崩溃：
                                      java.lang.NullPointerException: null
at com.huanchengfly.tieba.post.activities.ThreadActivity$q.onResponse(ThreadActivity.kt:3)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:3)
at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.b(null:0)
at retrofit2.b.run(null:6)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by Xnjikol** [comment]
疑似是点开被删除的帖子就会崩溃

**Comment by 5ec1cff** [comment]
![image](https://user-images.githubusercontent.com/56485584/175058589-688200ca-6b54-4b5e-b2be-f1b016f1b66b.png)

https://github.com/HuanCheng65/TiebaLite/blob/4.0-dev/app/src/main/java/com/huanchengfly/tieba/post/api/retrofit/interceptors/FailureResponseInterceptor.kt#L31

看起来是作者在调试的时候打了个 log ，结果把本来应该处理的异常 json 给读走了，导致未发现异常，进而 NPE 。

**Comment by HuanCheng65** [comment]
> ![image](https://user-images.githubusercontent.com/56485584/175058589-688200ca-6b54-4b5e-b2be-f1b016f1b66b.png)
> 
> https://github.com/HuanCheng65/TiebaLite/blob/4.0-dev/app/src/main/java/com/huanchengfly/tieba/post/api/retrofit/interceptors/FailureResponseInterceptor.kt#L31
> 
> 看起来是作者在调试的时候打了个 log ，结果把本来应该处理的 api 返回的错误 json 给截走了，导致未发现异常，进而 NPE 。
> 
> ![image](https://user-images.githubusercontent.com/56485584/175065431-aa582b23-1296-4bff-b12b-a1ab863901e1.png)

感谢！
