### ISSUE TITLE
点击个人主页后应用崩溃

### ISSUE THREAD

**Issue by D-Jancy** [HuanCheng65/TiebaLite#157]
如题，崩溃日志如下，机型小米12x，miui14
```log
                                      App 版本：4.0.0.80.dev-12
                                      系统版本：13
                                      机型：Xiaomi 2112123AC
                                      
                                      崩溃：
                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:26)
at rg.i.a(Source:144)
at rg.i$a.invokeSuspend(Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:12)
at og.p0.run(Source:125)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8261)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Xnjikol** [comment]
App 版本：4.0.0.80.dev-12
                                      系统版本：10
                                      机型：HUAWEI ELE-AL00
                                      
                                      崩溃：
                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:26)
at rg.i.a(Source:144)
at rg.i$a.invokeSuspend(Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:12)
at og.p0.run(Source:125)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by Xnjikol** [comment]
`                                      App 版本：4.0.0.80.dev-12
                                      系统版本：10
                                      机型：HUAWEI ELE-AL00
                                      
                                      崩溃：
                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:26)
at rg.i.a(Source:144)
at rg.i$a.invokeSuspend(Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:12)
at og.p0.run(Source:125)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
`

**Comment by HuanCheng65** [comment]
更新
