### ISSUE TITLE
最近一打开首页推荐就直接崩溃了

### ISSUE THREAD

**Issue by MikeCreeze** [HuanCheng65/TiebaLite#165]
之前偶尔打开一些帖子也会崩溃，跳转到主界面，现在首页推荐直接一点就崩溃了

**Comment by Daggycat** [comment]
是这样的 就从昨天开始一直闪退

**Comment by Accelerator-km** [comment]
我也是，完全刷不了贴了

**Comment by anklcaptain** [comment]
+1，不过是不是等不到更新了

**Comment by mario0729** [comment]
+1

**Comment by zyp997** [comment]
+1

**Comment by Freshball** [comment]
+1，最近官方贴吧推荐页多了一个“你关注的吧有精彩内容”的区域，个人猜测（纯猜）是json解析部分之类的地方因为上游结构变化报错了

**Comment by n0099** [comment]
> +1，不过是不是等不到更新了

https://github.com/HuanCheng65/TiebaLite/commits/4.0-dev
https://github.com/HuanCheng65/TiebaLite/issues/160#issuecomment-1440779948

**Comment by HuanCheng65** [comment]
4.0测试版本出现的问题吗？

**Comment by DSmegumi** [comment]
> 

是的，首页那里加载一会就闪退了

**Comment by Freshball** [comment]
> 4.0测试版本出现的问题吗？

我不是，release 3.8.3出现此问题，正在尝试编译dev-4.0测试

**Comment by DSmegumi** [comment]
> 

我现在鸿蒙3.0用4.0就会闪退

**Comment by Runninginsilence1** [comment]
2023年3月23日 18:18:20
我用as调试了下，贴一下日志：
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huanchengfly.tieba.post, PID: 4239
    kotlin.KotlinNullPointerException
        at com.huanchengfly.tieba.post.fragments.PersonalizedFeedFragment$refresh$1.onResponse(PersonalizedFeedFragment.kt:122)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:82)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6138)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
I/Process: Sending signal. PID: 4239 SIG: 9
Disconnected from the target VM, address: 'localhost:2026', transport: 'socket'

**Comment by Runninginsilence1** [comment]
因为没有做调试所以不提PR，没有条件的朋友可以下载我这份修改后的文件：https://wwwa.lanzouf.com/i1cls0qwguaf

**Comment by Runninginsilence1** [comment]
重新编译了一下，看上面原来是有4.0版本的...
我这个是基于3.8(release)那个版本改了一下
蓝奏云：https://wwwa.lanzouf.com/i1cls0qwguaf
