### ISSUE TITLE
[bug反馈]闪退

### ISSUE THREAD

**Issue by byz1234** [HuanCheng65/TiebaLite#181]
App 版本：4.0.0.63.dev-11
           系统版本：11
         机型：realme RMX3357
         崩溃：
                                      `java.lang.NullPointerException:` Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:7)
at id.k.a(Source:13)
at id.k$a.invokeSuspend(null:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:4)
at fd.o0.run(Source:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:255)
at android.app.ActivityThread.main(ActivityThread.java:8215)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)``

**Comment by byz1234** [comment]
App 版本：4.0.0.63.dev-11
    系统版本：11
   机型：realme RMX3357   
崩溃：                                 `java.lang.NullPointerException:` Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
> ```
> 
> at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:7) at id.k.a(Source:13) at id.k$a.invokeSuspend(null:11) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:4) at fd.o0.run(Source:18) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:255) at android.app.ActivityThread.main(ActivityThread.java:8215) at java.lang.reflect.Method.invoke(Method.java:-2) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)``
