### ISSUE TITLE
点击下载新版本后，开始无限崩溃

### ISSUE THREAD

**Issue by 498271674** [HuanCheng65/TiebaLite#189]
一顿狂点终于点到了复制崩溃报告

                                      App 版本：4.0.0.63.dev-11
                                      系统版本：11
                                      机型：Xiaomi MI 9 Transparent Edition
                                      
                                      崩溃：
                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.huanchengfly.tieba.post/com.microsoft.appcenter.distribute.install.ReleaseInstallerActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_INSTALL pkg=com.miui.packageinstaller (has extras) }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3540)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by 498271674** [comment]
哦，我这个是上古版本，会出好像挺正常的，但是我现在已经打不开APP了，该从哪下最新版捏

**Comment by n0099** [comment]
https://github.com/HuanCheng65/TiebaLite/issues/176#issuecomment-1514968868
