### ISSUE TITLE
点 个人页面 无限崩溃

### ISSUE THREAD

**Issue by HowToChooseName** [HuanCheng65/TiebaLite#194]
App 版本：4.0.0.80.dev-12
                                      系统版本：13
                                      机型：meizu meizu 17
                                      
                                      崩溃：
                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.huanchengfly.tieba.post.api.models.Profile$Anti.getTbs()' on a null object reference
at com.huanchengfly.tieba.post.fragments.MyInfoFragment$b$b.f(Source:26)
at rg.i.a(Source:144)
at rg.i$a.invokeSuspend(Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Source:12)
at og.p0.run(Source:125)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8045)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by HuanCheng65** [comment]
更新
