### ISSUE TITLE
回帖闪退，是不是有问题了这个软件

### ISSUE THREAD

**Issue by xiaozhong1** [HuanCheng65/TiebaLite#82]

**Comment by JadeButterfly** [comment]
我也是最近几天遇到的

**Comment by Karlex1337** [comment]
我也是，请修复谢谢！

**Comment by TWHking** [comment]
我也是

**Comment by pointm** [comment]
我也是，已经两天了

**Comment by PRO-2684** [comment]
我近几天也是这样

**Comment by ixuner** [comment]
同样问题

**Comment by kingling** [comment]
自行编译4.0.0也一样，详细信息如下，希望大佬速度救救孩子。
java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
	at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:14)
	at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.responseBodyConverter$lambda-0(NullOnEmptyConverterFactory.kt:18)
	at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.$r8$lambda$gOHAE2hymadNdqSx7OWcn7OAjcw(Unknown Source:0)
	at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory$$ExternalSyntheticLambda0.convert(Unknown Source:4)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by TWHking** [comment]
???发错人了吧 , 我是用户 , 我4版本回帖提示什么东西反正发不出去,&nbsp; 换成3点几的稳定版直接闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月1日(星期六) 下午2:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HuanCheng65/TiebaLite] 回帖闪退，是不是有问题了这个软件 (Issue #82)





 
自行编译4.0.0也一样，详细信息如下，希望大佬速度救救孩子。
 java.io.EOFException: End of input at line 1 column 1 path $
 at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395)
 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548)
 at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
 at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
 at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:14)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.responseBodyConverter$lambda-0(NullOnEmptyConverterFactory.kt:18)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.$r8$lambda$gOHAE2hymadNdqSx7OWcn7OAjcw(Unknown Source:0)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory$$ExternalSyntheticLambda0.convert(Unknown Source:4)
 at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
 at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
 
&mdash;

**Comment by TWHking** [comment]
我是用户 , 我4版本回帖提示什么东西反正发不出去,&nbsp; 换成3点几的稳定版直接闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuanCheng65/TiebaLite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 下午2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuanCheng65/TiebaLite] 回帖闪退，是不是有问题了这个软件 (Issue #82)





 
自行编译4.0.0也一样，详细信息如下，希望大佬速度救救孩子。
 java.io.EOFException: End of input at line 1 column 1 path $
 at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395)
 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548)
 at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
 at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
 at com.huanchengfly.tieba.post.api.retrofit.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:14)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.responseBodyConverter$lambda-0(NullOnEmptyConverterFactory.kt:18)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory.$r8$lambda$gOHAE2hymadNdqSx7OWcn7OAjcw(Unknown Source:0)
 at com.huanchengfly.tieba.post.api.retrofit.NullOnEmptyConverterFactory$$ExternalSyntheticLambda0.convert(Unknown Source:4)
 at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
 at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)

**Comment by Catdocode** [comment]
最近回帖总是返回：回贴失败(-1) End of input at line 1 column 1 path $ 这个错误，麻烦作者修复一下

**Comment by aawwsslll** [comment]
这软件还有人维护吗？看来是大家都回复不了。我也是3.8版本回复就闪退，希望可以尽快修复吧。

**Comment by Haerbin23456** [comment]
现在不能回帖惹

**Comment by yijvyan** [comment]
害，我也是，就很烦

**Comment by chriszhang1** [comment]
![Screenshot_20220106-133941](https://user-images.githubusercontent.com/75191238/148391698-d3b90b97-ef1f-492e-86c0-81df31ecbae1.jpg)

**Comment by xiaozhong1** [comment]
是的



| |
qq1656763216
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月31日 16:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [HuanCheng65/TiebaLite] 回帖闪退，是不是有问题了这个软件 (Issue #82) |

我也是最近几天遇到的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yijvyan** [comment]
回帖成功，看来百度抽风了
